import dotenv from 'dotenv';
dotenv.config();

const config = {
    TELEGRAM_TOKEN: process.env.TELEGRAM_TOKEN,
    CHAT_ID: process.env.CHAT_ID,
    EMAIL: process.env.WEB_EMAIL,
    PASSWORD: process.env.WEB_PASSWORD,
    PUBLIC_CHANNEL_TOKEN: process.env.PUBLIC_CHANNEL_TOKEN,
    WEATHERAPI_API_KEY: process.env.WEATHERAPI_API_KEY,
    LOCATION_NAME: process.env.LOCATION_NAME,
    SURF_REGISTERING_WEBSITE_LINK: process.env.SURF_REGISTERING_WEBSITE_LINK,
    SURF_FORECAST_LINK: process.env.SURF_FORECAST_LINK,
    DROPBOX_ACCESS_TOKEN: process.env.DROPBOX_ACCESS_TOKEN,
    DROPBOX_REFRESH_TOKEN: process.env.DROPBOX_REFRESH_TOKEN,
    DROPBOX_CLIENT_ID: process.env.DROPBOX_CLIENT_ID,
    DROPBOX_CLIENT_SECRET: process.env.DROPBOX_CLIENT_SECRET,
    SURF_REGISTERING_WEBSITE_MESSAGE_HEADER: process.env.SURF_REGISTERING_WEBSITE_MESSAGE_HEADER,
    // Debug/feature toggles
    ENABLE_TELEGRAM_PRIVATE: process.env.ENABLE_TELEGRAM_PRIVATE === 'true',
    ENABLE_TELEGRAM_PUBLIC: process.env.ENABLE_TELEGRAM_PUBLIC === 'true',
    ENABLE_DROPBOX_DOWNLOAD: process.env.ENABLE_DROPBOX_DOWNLOAD === 'true',
    ENABLE_DROPBOX_UPLOAD: process.env.ENABLE_DROPBOX_UPLOAD === 'true'
};

export default config;